//SIGNUP
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED'
export const RESET_USER_SIGNUP = 'RESET_USER_SIGNUP'
export const LOADING_USER_SIGNUP = 'LOADING_USER_SIGNUP'
export const USER_SIGNUP_NETWORK_ERROR = 'USER_SIGNUP_NETWORK_ERROR'

//LOGIN
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const RESET_USER_LOGIN = 'RESET_USER_LOGIN'
export const LOADING_USER_LOGIN = 'LOADING_USER_LOGIN'
export const USER_LOGIN_NETWORK_ERROR = 'USER_LOGIN_NETWORK_ERROR'
